issues/urls.py
from django.urls import path

from .views import (
    IssueListView,
    IssueDetailView,
    IssueCreateView,
    IssueUpdateView,
    IssueDeleteView,


)


urlpatterns = [
    path("list/", IssueListView.as_view(), name="issue-list"),
    path("<int:pk>/", IssueDetailView.as_view(), name="issue-detail"),
    path("create/", IssueCreateView.as_view(), name="issue-create"),
    path("<int:pk>/uptade", IssueUpdateView.as_view(), name="issue-update"),
    path("<int:pk>/delete", IssueDeleteView.as_view(), name="issue-delete"),

]

registers/urls.py
from django.urls import path

from . views import (
    RegisterListView,
    RegisterCreateView,
    RegisterUpdateView,
    RegisterDetailView,
    RegisterDeleteView,
    pdffile,
)




urlpatterns = [
    path("list", RegisterListView.as_view(), name="register-list"),
    path("<int:pk>/", RegisterDetailView.as_view(), name="register-detail"),
    path("create/", RegisterCreateView.as_view(), name="register-create"),
    path("<int:pk>/update/", RegisterUpdateView.as_view(), name="register-update"),
    path("delete/<int:pk>/", RegisterDeleteView.as_view(), name="register-delete"),
    path("pdf/", pdffile, name="register-pdf"),

]

rentalApp/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import IndexView

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("admin/", admin.site.urls),
    path("register/", include("registers.urls")),
    path("statement/", include("statements.urls")),
    path("invoice/", include("invoices.urls")),
    path("issue/", include("issues.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registers/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse
from django.utils import timezone




class Register(models.Model):
    RENT_TYPE = [("chambre", "chambre"), ("studio", "studio"), ("appartement", "appartement")]

    full_name = models.CharField("Enter Full Name",  max_length=250)
    cni_no = models.IntegerField(unique=True)
    rent_type = models.CharField(max_length=15, choices=RENT_TYPE)
    mobile_num_regex = RegexValidator(
        regex="^[0-9]{10,15}$", message="Entered mobile number isn't in a right format!"
    )
    phone = models.CharField("Phone number", validators=[mobile_num_regex], max_length=13, blank=True)
    email = models.EmailField(unique=True)
    address = models.CharField("Street address", max_length=150)
    date = models.DateField("Start date", default=timezone.now)
    amount = models.IntegerField("Amount paid")


    class meta:
        ordering = ["full_name" "rent_type" "email"]


    def __str__(self):
        return f"{self.full_name} - {self.rent_type} - {self.email}"


    def get_absolute_url(self):
        return reverse("register-detail", kwargs={"pk": self.pk})

    

    

registers/views.py
from django.shortcuts import render

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.messages.views import SuccessMessageMixin
from django.forms import widgets
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from . models import Register

#some importations to use with reportlab in generate pdf file in django
import io
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter,C7,C11
########


class RegisterListView(LoginRequiredMixin, ListView):
    model = Register
    template_name = "registers/register_list.html"
    context = Register.objects.all()


class RegisterCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Register
    fields = "__all__"
    success_message = "New record successfully added."

    def get_form(self):
        """add date picker in forms"""
        form = super(RegisterCreateView, self).get_form()
        form.fields["date"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        return form


class RegisterUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Register
    fields = "__all__"
    success_message = "Record successfully updated."

    def get_form(self):
        """add date and text picker in forms"""
        form = super(RegisterUpdateView, self).get_form()
        form.fields["date"].widget = widgets.DateInput(attrs={"type": "date"})
        form.fields["address"].widget = widgets.Textarea(attrs={"rows": 2})
        return form
        


class RegisterDetailView(LoginRequiredMixin, DetailView):
    model = Register
    template_name = "registers/register_detail.html"

    def get_context_data(self, **kwargs):
        context = super(RegisterDetailView, self).get_context_data(**kwargs)
        return context

    

class RegisterDeleteView(LoginRequiredMixin, DeleteView):
    model = Register
    success_url = reverse_lazy("register-list")



def pdffile(request):
    buffer = io.BytesIO()

    c = canvas.Canvas(buffer, pagesize=letter)

    DocumentTitle = 'New invoice generator'

    c.setTitle(DocumentTitle)

    c.translate(inch,inch)
    # define a large font
    c.setFont("Helvetica", 14)
    # choose some colors
    c.setStrokeColorRGB(0.1,0.8,0.1)
    c.setFillColorRGB(0,0,1) # font colour
    #c.drawImage('C:\Users\new_user\Pictures\Screenshots\Capture d’écran (1).png',-0.8*inch,9.3*inch)
    c.drawString(0, 9*inch, "City Name : ")
    c.drawString(0, 8.7*inch, "Address : ")
    c.setFillColorRGB(0,0,0) # font colour
    #c.line(0,8.6*inch,6.8*inch,8.6*inch)
    c.drawString(4.9*inch,9.5*inch,'Invoice No :# 854')
    from  datetime import date
    dt = date.today().strftime('%d-%b-%Y')
    c.drawString(5.6*inch,9.3*inch,dt)
    c.setFont("Helvetica", 18)
    c.drawString(3*inch,9.6*inch,'Register List')
    c.setFillColorRGB(1,0,0) # font colour
    c.setFont("Times-Bold", 30)
    c.drawString(4.3*inch,8.7*inch,'Invoice')
    c.rotate(45) # rotate by 45 degree 
    c.setFillColorCMYK(0,0,0,0.08) # font colour CYAN, MAGENTA, YELLOW and BLACK
    c.setFont("Helvetica", 80) # font style and size
    c.drawString(1.8*inch, 0.4*inch, "SAUVEGARDE") # String written 
    c.rotate(-45) # restore the rotation #good to know
    c.setFillColorRGB(0,0,0) # font colour
    c.setFont("Times-Roman", 22)
    c.drawString(0, 8.3*inch,'Name')
    c.drawString(2*inch, 8.3*inch, 'Rent type')
    c.drawString(3.7*inch,8.3*inch,'Email')
    c.drawString(5.1*inch,8.3*inch,'Phone')
    c.drawString(6.2*inch,8.3*inch,'Start date')
    registers = Register.objects.all()
    #line_y = 7.9
    for register in registers:
        c.setFont("Helvetica", 9)
        c.drawString(0, 8*inch, f'{register.full_name}')
        c.drawString(2*inch, 8*inch, f'{register.rent_type}')
        c.drawString(3.6*inch, 8*inch, f'{register.email}')
        c.drawString(5.1*inch, 8*inch, f'{register.phone}')
        c.drawString(6.2*inch, 8*inch, f'{register.date}')




    c.setStrokeColorCMYK(0,0,0,1) # vertical line colour
    c.line(1.6*inch,8.3*inch,1.6*inch,0*inch)# first vertical line
    c.line(3.5*inch,8.3*inch,3.5*inch,0*inch)# second vertical line
    c.line(4.9*inch,8.3*inch,4.9*inch,0*inch)# third vertical line
    c.line(6.1*inch,8.3*inch,6.1*inch,0*inch)# fourth vertical line
    c.line(0.01*inch,0*inch,8*inch,0*inch)# horizontal line total
    c.setFont("Helvetica", 8) # font size
    c.setFillColorRGB(1,0,0) # font colour
    c.drawString(0, -0.1*inch, u"\u00A9"+" Light_35") 
        
    c.save()
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='register.pdf')

        #create a file like buffer to receive PDF data
        #buffer = io.BytesIO()

        #create the PDF object, using the buffer as its "file"
        #p = canvas.Canvas(buffer, pagesize=letter, bottomup=0)

        #Draw things on the PDF. here's where the pdf generation happens.
        #see the reportlab documentation for the full list of functionnality.
        
    

        #Create a text object
        #textob = p.beginText()
        #textob.setTextOrigin(inch, inch)
        #textob.setFont("Helvetica", 14)

        #Designate the model
        #registers = Register.objects.all()
        #lines = []
        #for register in registers:
            #lines.append(f'{register.full_name}')
            #lines.append(f'{register.rent_type}')
            #lines.append(f'{register.email}')
            #lines.append(f'{register.phone}')
            #lines.append(f'{register.address}')
            #lines.append(f'{register.date}')
            #lines.append(f'{register.amount}')
            #lines.append('=================================') """

        #Loop
        #for line in lines:
            #textob.textLine(line)

        #Finish up
        #p.setTitle("Register's pdf")
        #p.drawCentredString(270, 30, "REGISTRATION RECORD")
        #p.drawText(textob)


        #close the pdf object cleanly, and we're done
        #p.showPage()
        #p.save()

        #FileResponse sets the content-Disposition header so that browsers present the option to save the files.
        #buffer.seek(0)
        #return FileResponse(buffer, as_attachment=True, filename='register.pdf') """

registers/templates/registers/register_confirm_delete.html
{% extends 'base.html' %}


{% block title %}
{% endblock title %}


{% block content %}

<form action="" method="POST">
  {% csrf_token %}

  <div class="alert">
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <p>All contents attached to this student will be deleted</p>
  </div>

  <input type="submit" class="btn btn-primary" value="Confirm">

</form>


{% endblock content %}

registers/templates/registers/register_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content-header %}
<div class="card-header">
  <div class="card-tools">
    <a href="{% url 'register-pdf' %}" class="btn btn-tool">Print</a>
    <a href="{% url 'register-update' object.id %}" class="btn btn-tool">
      <i class="fas fa-edit"></i>
    </a>
    <a href="{% url 'register-delete' object.id %}" class="btn btn-tool">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>
{% endblock content-header %}

{% block content %}
    <div class="row mb-4">
      <div class="col-sm-4">
        <div class="row mb-2">

          <!-- {% if object.passport %}
            <img
              src="{{ object.passport.url }}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% else %}
            <img
              src="{% static 'dist/img/avatar.png' %}"
              class="float-left rounded-circle mr-3" style="width: 120px; height: 120px;">
          {% endif %} -->


          <div class="float-right">
            <h4>{{ object.full_name }} </h4>
            <h4>{{ object.email }} </h4>
            <h4>{{ object.phone }} </h4>
            <h4>{{ object.rent_type }} </h4>
          </div>
        </div>

      </div>
      <div class="col-sm-8">
        <div>
          <div class="form-group border-bottom row">
            <label class="col">
              Start date
            </label>
            <div class="col">
              {{ object.date }}
            </div>
          </div>

          <div class="form-group border-bottom row">
            <label class="col">
              Address
            </label>
            <div class="col">
              {{ object.address }}
            </div>
          </div>

        </div>

      </div>
    </div>

    <h4>Invoice/Payment History</h4>
    <!-- {% if payments %}
      <table class="table table-sm table-bordered table-hover">
        <thead class="thead-light">
          <tr>
            <th>For</th>
            <th>Amount Payable</th>
            <th>Amount Paid</th>
            <th>balance</th>
          </tr>
        </thead>
        <tbody>
          {% for payment in payments %}
            <tr class='clickable-row' data-href="{% url 'invoice-detail' payment.id %}">
              <td>{{payment.session}} - {{payment.term}} - {{ payment.class_for}}</td>
              <td>{{payment.total_amount_payable}}</td>
              <td>{{payment.total_amount_paid}}</td>
              <td>{{payment.balance}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
        <p>There are no payment history for {{object}}</p>
    {% endif %}
 -->



{% endblock content %}

registers/templates/registers/register_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}



{% block title %}

  {% if object %}
    Update {{ object }}
  {% else %}
    Add new record
  {% endif %}

{% endblock title %}


{% block content %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% for field in form %}
  <div class="form-group row">
    <label class="col-sm-3 col-form-label" for="{{ field.auto_id }}">
      {{ field.label }}
      {% for error in field.errors %}
        <small id="{{ field.auto_id }}" class="text-danger">{{ error }}</small>
      {% endfor %}
    </label>
    <div class="col-sm-9">
      {{ field | add_class:"form-control"}}
      {% if field.help_text %}
      <small>{{ field.help_text|safe }}</small>
      {% endif %}
    </div>
  </div>
  {% endfor %}
  

  {% if object %}
    <input type="submit" class="btn btn-primary" value="Update Record">
  {% else %}
    <input type="submit" class="btn btn-primary" value="Add new Record">
  {% endif %}
</form>


{% endblock content %}

registers/templates/registers/register_list.html
{% extends 'base.html' %}

{% block title %}register{% endblock title %}

{% block breadcrumb %}
<a class="btn btn-primary" href="{% url 'register-create' %}"><i
    class="fas fa-plus"></i> New record</a>
<a class="btn btn-primary" href="#"><i
    class="fas fa-upload"></i> Upload record</a>
{% endblock breadcrumb %}

{% block content %}
  <div class="table-responsive">
    <table id="studenttable" class="table table-bordered table-hover" data-page-length='100'>
      <thead class="thead-light">
        <tr>
          <th>S/N</th>
          <th>Fullname</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Start date</th>
          <th>Rent typ</th>
        </tr>
      </thead>
      <tbody>

        {% for register in object_list %}
          <tr class='clickable-row' data-href="{% url 'register-detail' register.id %}">
            <td>{{ forloop.counter }}</td>
            <td>{{ register.full_name }}</td>
            <td>{{ register.phone }}</td>
            <td>{{ register.email }}</td>
            <td>{{ register.date }}</td>
            <td>{{ register.get_rent_type_display }}</td>
          </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
{% endblock content %}


{% block morejs %}
<script>
  $('#studenttable').DataTable({
  });
</script>

{% endblock morejs %}